#' Function to create a concordance from a filtered corpus data.frame
#' @description This function will create a concordance for a string or regex pattern 
#' @param filtered_corpus a data.frame generated by searchCorpus or by calling command-line grep on the corpus files
#' @param pattern a regex pattern. If you want to match full-word strings, just pad your string with the word boundary symbol \code{\\b}. E.g. \code{\\b(brother)\\b}
#' @param column column to match the pattern against. The column 'text' contains the untagged text, the column 'text' contains the dependency-tagged text
#'
#' @return a data.frame with a conconcordance for your pattern added to the input data.frame
#' @export
#' @import dplyr
#' @import parallel
#' @import stringi
#'
#' @examples this function can be combined with searchCorpus in a corpus-processing pipeline. For example: \code{concordance<-searchCorpus() %>% 
#' makeConcordance() }
makeConcordance <- function(filtered_corpus, pattern=NULL, column = c("tagged", "text") )
{
  options(mc.cores=parallel::detectCores())
  if(is.null(pattern)) {
    stop("You must define a search pattern for your concordance.")
  }
  column<-match.arg(column)
  dataFrame <- as.data.frame(filtered_corpus)
  lines <- mcmapply(dataFrame[, column], dataFrame[,"id"], SIMPLIFY = F, FUN = function(x, y) {
    token <- stri_extract_all_regex(x, pattern)[[1]]
    splits <- stri_split_regex(x, pattern)
    before <- vector("character", length(token))
    after <- vector("character", length(token))
    id_str <- y
    for	(i in 1:length(token))
    {
      before[i] <- splits[[1]][i]
      after[i] <-  splits[[1]][i + 1]
    }
    return(data.frame(before = before, token = token, after = after, id_str = id_str,
                      stringsAsFactors = F))
  })
  concordance <- bind_rows(lines) %>%
  left_join(dataFrame, join_by="id")) %>%
  filter(!duplicated(after))
  return(concordance)
}
