# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fuzzyMatch <- function(needles, haystack, maxDistance, nthreads = 1L, displayProgress = TRUE) {
    .Call('_tweetCorp_fuzzyMatch', PACKAGE = 'tweetCorp', needles, haystack, maxDistance, nthreads, displayProgress)
}

